name: moviedb_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  marquee: ^2.2.3
  number_paginator: ^0.2.3
  flutter_bloc: ^8.1.3
  #freezed: ^2.4.2
  #freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.0
  equatable: ^2.0.5
  #get_it: ^1.5.3
  injectable: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 
  json_serializable: ^6.7.1
  


flutter:
  uses-material-design: true

  assets:
    - assets/images/Anime.jpg
    - assets/images/Your Name.jpg
